### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Calinou** [KaneRoot/dnsmanager#1]
Je n'ai pas trouvé de licence pour ce projet, il serait bien d'en ajouter une. [Plus d'information (en anglais)](http://choosealicense.com/).

**Comment by KaneRoot** [comment]
Je sais, je me pose encore la question de quelle licence utiliser. Il faut que ce soit compatible avec les bibliothèques que j'utilise.

**Comment by KaneRoot** [comment]
J'ai décidé de mettre mon code sous licence ISC.
