### ISSUE TITLE
probleme renouvellement

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#13]
J'ai un problème avec le renouvellement (ça ne semble pas venir des scripts qui ont l'air d'afficher les bonnes infos).
L'adresse IP de mon serveur est bonne dans "Ma page" sur netlib.re, par contre quand je tape "dig www.mondomaine.netlib.re" c'est la précédente IP qui est encore affichée.
Quand je ping ça joint aussi la précédente IP, idem quand je tente de joindre via Tor Browser.

**Comment by KaneRoot** [comment]
Pour t'aider il me faudrait ton pseudo ou ton vrai nom de domaine sur netlib.re.

**Comment by ghost** [comment]
Ça a l'air revenu. Peut-être une latence dans le renouvellement d'un cache (d'un dns secondaire ou des navigateurs mais je pense pas que Tor Browser conserve un quelconque cache quand on le quitte).
C'est le domaine www. 0rion qui était tombé en rade après un changement d'IP peu de temps après que j'ai posté l'article sur LinuxFR :O
