### ISSUE TITLE
Nom de domaine down, mauvaise ip répondue par les DNS

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#14]
Depuis 2-3 jours www.0rion.netlib.re (entre autre) est down.
D'après ma page sur https://netlib.re, l'adresse IP est bonne et se renouvelle correctement.
Mais lorsqu'on dig le nom de domaine , une mauvaise adresse IP est répondue. ([voir ici](http://paste.arn-fai.net/?2850231))

**Comment by KaneRoot** [comment]
Je ne suis pas sûr de ce qu'il s'est passé, cependant je viens d'ajouter puis supprimer une entrée depuis l'interface `netlib.re` et la zone s'est bien mise à jour sur le serveur de noms d'ARN, et cela répond correctement. Donc je te laisse répondre à ce message pour me confirmer que c'est bon pour toi avant de fermer l'issue sur github.

**Comment by voxdemonix** [comment]
Hélas non,, ça continue de me renvoyer une mauvaise IP (une précédente je suppose).

![Uploading Screenshot_2018-09-27_13-26-29.png…]()

**Comment by ghost** [comment]
Hélas non, ça continue de me renvoyer une mauvaise IP (une précédente je suppose).

![screenshot_2018-09-27_13-26-29](https://user-images.githubusercontent.com/8572474/46143236-acb1a000-c259-11e8-88df-2bba2744db3c.png)

**Comment by KaneRoot** [comment]
Est-ce que tu as vidé ton cache DNS ? Quel est le résolveur que tu utilises ? Parce que sur `ns0.arn-fai.net` et sur `alsace.tetaneutral.net` (nos deux serveurs de noms), l'IP renvoyée est `91.180.151.185`.

**Comment by ghost** [comment]
Le screenshot c'est après reboot de la machine (donc cache propre, resolveur par defaut (netmasq de network-manager)). J'ai supprimé puis recréé les quasi toutes les entrées et, après un moment très confus, ça semble s'être remis en fonction. Modifier une entrée semble a nouveau fonctionner aussi.

Gros merci Karchnu.

**Comment by KaneRoot** [comment]
Tu as aussi un cache sur ta machine, certes, mais je parlais du cache de ton résolveur. C'est toujours plus ou moins le soucis qu'on rencontre quand on manipule du DNS, le cache du résolveur n'est pas mis à jour aussi vite qu'on voudrait tester… bref. Content que ton problème soit résolu. :-)
