### ISSUE TITLE
Champs SPF ?

### ISSUE THREAD

**Issue by weber-s** [KaneRoot/dnsmanager#15]
Bonjour,

Est-ce qu'il serait facile d'avoir le champs SPF éditable en mode "expert" ?

Je n'y connais rien en perl, mais puisque'il y a déjà quelque chose comme ca dans `lib/zonefile.pm`

```perl
        elsif($list[3] =~ /^TXT$/) {
            $$rr{rdata} = $_->rdstring;
            utf8::decode($$rr{rdata});
}
```
ajouter ca en dessous : 
```perl
        elsif($list[3] =~ /^SPF$/) {
            $$rr{rdata} = $_->rdstring;
            utf8::decode($$rr{rdata});
}
```
ca devrait le faire ?

Merci pour Netlib.re !!

**Comment by KaneRoot** [comment]
En réalité, ça dépend de la bibliothèque qui gère les resource records. Je verrai ça quand j'aurai un peu de temps (mais il me semble bien qu'elle ne le gérait pas aux dernières nouvelles). Will see.

**Comment by KaneRoot** [comment]
Les enregistrements de type SPF étant obsolètes, je clos ce fil de discussion.
