### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#2]
Lorsque je tente un update via IPV6 l'interface d'administration "Fichier de zone" affiche comme adresse IP 0.0.0.2 pourtant dans le shell je vois bien la bonne adresse IPV6.
En IPV4 ça tourne sans problème :)
merci ;)

**Comment by KaneRoot** [comment]
J'ai amélioré le script pour qu'il force l'usage d'IPv4 si on indique un type "A" et d'IPv6 si on indique le type "AAAA". Chez moi ça fonctionne bien, vous pouvez essayer de votre côté et me confirmer que le problème est résolu ?

Merci pour la contribution. :)

**Comment by ghost** [comment]
Ça marche ! Réactivité 10/10 kaneRoot ^^
A noter qu'il faut :
supprimer l'entrée sur netlib puis la re-créer  avec comme tu as dit avec comme type : "AAAA" (par contre dommage qu'on ne peut pas ajouter l'entrée avec l'IP vide pour ensuite la mettre a jours via le script).

Solved !

**Comment by KaneRoot** [comment]
Pour la réactivité c'est assez simple, j'ai arrêté de dormir l'année dernière.

Je ne considère pas la suppression d'une entrée A pour la remplacer par une entrée AAAA comme une erreur. Avant j'avais fait en sorte qu'on puisse changer le type de l'entrée, mais ça n'a que peu d'intérêt, et ça alourdit (légèrement) l'interface. J'ai donc décidé de supprimer cette possibilité.

**Comment by ghost** [comment]
Tu devrais le signaler dans la page d'administration de netlib afin d'éviter que d'autres te reposent la même question indéfiniment :)
Je souhaite migrer mon frontend vers une connexion disposant d'ipv4 et ipv6, sais-tu s'il est possible d'avoir une même url ou suis-je obligé d'avoir deux url distinct (une pour ipv4 et une pour ipv6)? (ma question est ptete stupide, je suis nouveau dans le monde de l'ipv6 ^^)

**Comment by KaneRoot** [comment]
Tu peux avoir deux enregistrements de même nom, l'un avec un type A et un autre en type AAAA. En vrai tu peux aussi avoir plusieurs enregistrements de même nom et de même type si tu veux, mais pour un particulier c'est rarement utile. ;)

Il faudra lancer 2 fois le script, une fois avec ton IPv4 et une pour ton IPv6, bien que celle-ci ne devrait pas changer… sauf si ton fournisseur d'accès à Internet change régulièrement de préfixe (je ne sais pas ce qu'il se fait actuellement dans le grand public).
