### ISSUE TITLE
Connexion refusée

### ISSUE THREAD

**Issue by matthiasbe** [KaneRoot/dnsmanager#20]
J'ai pu créer un compte sans problème, mais impossible de m'y reconnecter plus tard.
Cela vient peut-être du fait que j'ai générer un mot de passe trop compliqué ? (30 caractère dont des caractères spéciaux).

C'est surtout pour vous notifier du problème, car j'ai créer un deuxième compte avec un autre mot de passe, et la reconnexion s'est bien passé. (celui là 20 caractères sans caractères spéciaux)

**Comment by KaneRoot** [comment]
Salut, je ne sais pas ce qu'il s'est passé. De mémoire je n'ai mis aucune limite sur le contenu des mots de passe.
