### ISSUE TITLE
erreur sur l'interface web netlib.re lorsqu'on veux visionner les détails du domaine

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#4]
Sur le site web de netlib.re, dans la page "Ma page" lorsque je clique sur "Détails" de n'importe quel domaine. J'ai l'erreur suivante :

> Oh ! Une erreur est survenue. scp failed: unable to fork ssh master: Ne peut allouer de la mÃ©moire at /home/ppittoli/dnsmanager/bin/../lib/copycat.pm line 35. 

Je n'arrive plus à faire fonctionner le client non plus, le client reçoit une redirection vers la page d'accueil je ne sais pas si c'est normal :

> Connexion à netlib.re (netlib.re)|89.234.141.68|:443… connecté.
> requête HTTP transmise, en attente de la réponse… 302 Found
> Emplacement : https://netlib.re/ [suivant]

(et en effet quand je tente de suivre le même lien que le wget dans le Shell, je suis redirigé vers la page d'accueil)

**Comment by KaneRoot** [comment]
C'est un problème qui m'arrive régulièrement, je pense que c'est lors d'un fork (pour récupérer ou envoyer des données vers les serveurs DNS en ssh) qu'il y a un soucis. Je fais le fork, mais je n'attend pas le code de retour du fils, du coup il reste là. Si c'est ça, c'est un problème dans la documentation de Net::OpenSSH qu'il manquerait ça.

La solution en attendant c'est de redémarrer le programme régulièrement. Je corrigerai quand j'aurai un peu de temps devant moi.

En attendant je fais du curatif, je reboot régulièrement l'appli, ça devrait plus se produire.
