### ISSUE TITLE
problème avec le certificat Let's Encrypt

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#6]
Peut-être est-ce un problème temporaire le temps que Let's Encrypt soit reconnu partout (dans le doute, je signale le soucis :) )
wget ne reconnaît pas la validité du certificat de netlib.re, il faut lui ajouter l'option "--no-check-certificate" (à la fin de la ligne 51 par exemple, juste avant le dernier guillemet) pour que le script d'update recommence à fonctionner :)

> Connexion à netlib.re (netlib.re)|89.234.141.68|:443… connecté.
> Erreur : impossible de vérifier l'attribut netlib.re du certificat, émis par «/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3» :
>   Impossible de vérifier localement l'autorité de l'émetteur.
> Pour établir une connexion non sécurisée à netlib.re, utilisez « --no-check-certificate ».

**Comment by KaneRoot** [comment]
Cela sonne bien comme un problème temporaire sur ta machine. Le certificat est valide et fonctionne très bien chez d'autres utilisateurs. Merci quand même du signalement. :)
