### ISSUE TITLE
multiple mots de passe

### ISSUE THREAD

**Issue by ghost** [KaneRoot/dnsmanager#8]
Pour renforcer la sécurité contre la compromission d'une machine (pour ceux qui ont plusieurs noms de domaine sur le même compte utilisateur), il pourrait être intéressant de reprendre le mécanisme de Nextcloud.
Ce dernier permet en deux clics de créer des mots de passe aléatoire lié à un label du genre "machine de toto" et de  connaître la date et heure de la dernière activité.
Vous pouvez voir un exemple de ce mécanisme dans mon tuto sur la [synchro de fichier avec nextcloud](https://linuxfr.org/wiki/tuto-comment-synchroniser-des-dossiers-fichiers-sur-nextcloud-ou-owncloud).

**Comment by KaneRoot** [comment]
Ça peut être intéressant, et j'accepte volontier un patch + un script pour màj la BDD, mais je ne ferai pas ça moi-même, je manque de temps.
